spring:
    datasource:
      readSize: 1
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://localhost:3306/springboot_demo
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver