spring:
    datasource:
      readSize: 1
      name: writeDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver

    #thymeleaf开发环境关闭thymeleaf缓存
    thymeleaf:
#      prefix: classpath:/templates/
      prefix: classpath:/static/html/
      suffix: .html
      cache: false
      mode: LEGACYHTML5
      encoding: utf-8
      content-type: text/html

      #
server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
security:
  ignored: /**


##验证码工具
#kaptcha:
#  session:
#    key: kaptcha.code
#  #border: no
#  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
#  obscurificator:
#    impl: com.google.code.kaptcha.impl.WaterRipple
#  #不要噪点
#  noise:
#    impl: com.google.code.kaptcha.impl.NoNoise
#  image:
#    width: 90
#    height: 33
#  textproducer:
#    font:
#      size: 25
#      color: black
#    char:
#      length: 4
#      space: 5
#  #和登录框背景颜色一致
#  background:
#    clear:
#      from: 247,247,247
#      to: 247,247,247