spring:
    datasource:
      readSize: 1
      name: writeDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver



    #thymeleaf开发环境关闭thymeleaf缓存
    thymeleaf:
#      prefix: classpath:/templates/
      prefix: classpath:/static/ace/html/
      suffix: .html
      cache: false
      mode: LEGACYHTML5
      encoding: utf-8
      content-type: text/html
      #
server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
security:
  ignored: /**
